name: CI

on: [push]

jobs:
  lint:
    strategy:
      fail-fast: true
      matrix:
        python-version: [ '3.10' ]
        os: [ ubuntu-latest ]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - name: Install dependencies
        run: |
          pipenv install -d
      - name: Look for style errors
        run: pipenv run pflake8
      - name: Check for importing style
        run: pipenv run isort --profile=black --check --diff .
      - name: Look for auto format errors
        run: pipenv run black --check --diff . --target-version py310